es:
  host: '192.168.0.64'
  port: '9200'
  cluster: 'superheromatch'
  index: 'superhero'

db:
  host: '192.168.0.64'
  port: 3306
  user: 'dev'
  password: 'Awesome85**'
  name: 'municipality'

consumer:
  brokers: ['192.168.0.64:9092']
  topic: 'delete.municipality.superhero'
  group_id: 'consumer.superhero.delete.group'

health:
  port: ':8060'
  shutdown_endpoint: '/api/v1/consumer_superhero_delete_health/shutdown'
  content_type: 'application/json'